### ISSUE TITLE
Path parameter validation appears broken.

### ISSUE THREAD

**Issue by brad-jones** [carlansley/swagger2#18]
Either I am missing something obvious or the request validation method needs to also have the actual path passed in so that it can be validated.

ie:

```ts
function request(compiledPath: CompiledPath | undefined,
                        path: string,
                        method: string,
                        query?: any,
                        body?: any,
                        headers?: any): ValidationError[] | undefined
```

Or make use of the parsing already doen by the like koa, express and others and just ask for a parameters object, ie:

```ts
function request(compiledPath: CompiledPath | undefined,
                        pathParameters: { [name: string]: any },
                        method: string,
                        query?: any,
                        body?: any,
                        headers?: any): ValidationError[] | undefined
```

And then this:

```ts
case 'path':
        const actual = compiledPath.name.match(/[^\/]+/g);
        const valueIndex = compiledPath.expected.indexOf('{' + parameter.name + '}');
        value = actual ? actual[valueIndex] : undefined;
        break;
```

becomes something like:

```ts
case 'path':
        value = (pathParameters || {})[parameter.name];
        break;
```

I have basically just hacked my local javascript inside node_modules and now path parameters are begin validated correctly in my Koa app.

**Comment by carlansley** [comment]
Yeah this is a bug, not something I've come across before since we always treat path parameters as simple strings.

**Comment by carlansley** [comment]
Happy to accept a PR for this one if its urgent for you, can probably fix it myself next week at some point.
