### ISSUE TITLE
Is it possible to include template strings in the document?

### ISSUE THREAD

**Issue by bag-man** [carlansley/swagger2#28]
I would like to include [templated strings](https://swagger.io/docs/specification/api-host-and-base-path/) for the server, but this doesn't appear to be supported with `loadDocumentSync`. 

Am I missing something, or would it need to be added as a feature?

**Comment by carlansley** [comment]
I believe this is an OpenAPI 3 feature, this project only supports Swagger v2.  However we are working on a new project that supports both, will update the documentation here once it is ready.
